#!/usr/bin/env python3

from sys import stdin

if __name__ == "__main__":
    
    #Get the STDIN expected input to be piped in
    txt = ""

    #Below method of inputting to EOF by arekolek, https://stackoverflow.com/questions/21235855/how-to-read-user-input-until-eof
    for intext in stdin:
        txt += intext
    words = txt.lower().split()
    
    #Select just the all alphabet words
    alphawords = []
    for w in words:
        if w.isalpha() and w.isascii():
            alphawords.append(w)
        
    #Counting most letters in each words.
    letters = {}
    total = 0
    for w in alphawords:
        
        #Method of counting frequency found here: https://www.geeksforgeeks.org/python-frequency-of-each-character-in-string/
        for l in w:
            if l in letters:
                letters[l] += 1
            else:
                letters[l] = 1
        #Add to the total the value of the most frequent letter.
        total += max(letters.values())
        #Clear the dict before running again
        letters.clear()
        
    print(total)
